GET http://localhost:8080/system/api/v1/users
Accept: application/json

###

GET http://localhost:8080/system/api/v1/users/2
Accept: application/json

###

GET http://localhost:8080/system/api/v1/users/username/jmonetti
Accept: application/json

###

POST http://localhost:8080/system/api/v1/users
Content-Type: application/json

{
  "username": "jlowkey",
  "password": "hashed_password123",
  "email": "jlowkey@gmail.com",
  "name": "jlo",
  "rol": "ROLE_USER"
}

###

POST http://localhost:8080/system/api/v1/users/register
Content-Type: application/json

{
  "username": "jlowkeyREGISTER",
  "password": "hashed_password123",
  "email": "jlowkeyREGISTER@gmail.com",
  "name": "jlo"
}

###

PUT http://localhost:8080/system/api/v1/users/7
Content-Type: application/json

{
  "username": "jhighkey",
  "password": "hashed_password456",
  "email": "jhighkey@gmail.com",
  "name": "jhi",
  "rol": "ROLE_ADMIN"
}

###

DELETE http://localhost:8080/system/api/v1/users/7
Accept: application/json

###

GET http://localhost:8080/system/api/v1/users/1/tasks
Accept: application/json

###

POST http://localhost:8080/system/api/v1/users/2/tasks
Content-Type: application/json

{
  "name": "Tarea prueba 1",
  "status": "PENDING",
  "dueDate": "2024-12-13T00:00:00",
  "userId": 1
}

###

GET http://localhost:8080/system/api/v1/users/2/tasks/5
Accept: application/json

###

PUT http://localhost:8080/system/api/v1/users/2/tasks/5
Content-Type: application/json

{
  "name": "Tarea prueba 2222",
  "status": "PENDING",
  "dueDate": "2024-12-14T00:00:00"
}

###

DELETE http://localhost:8080/system/api/v1/users/2/tasks/5
Accept: application/json


###

GET http://localhost:8080/system/api/v1/users/3/tasks/filter?status=IN_PROGRESS
Accept: application/json




